services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: speak
      POSTGRES_PASSWORD: speakpass
      POSTGRES_DB: speaktrainer
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Expose ML service port
    volumes:
      - ./ml/src:/app/src
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO

  api:
    build: ./api
    depends_on:
      - db
      - ml-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://speak:speakpass@db:5432/speaktrainer
      ML_SERVICE_URL: http://ml-service:8001  # Use container name
      ENVIRONMENT: development

  # web:
  #   build: ./web
  #   depends_on:
  #     - api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_API_URL: http://localhost:8000  # This is correct for browser

volumes:
  pgdata: