services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: speak
      POSTGRES_PASSWORD: speakpass
      POSTGRES_DB: speaktrainer
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
      - ml-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://speak:speakpass@db:5432/speaktrainer?sslmode=disable
      ML_SERVICE_URL: http://ml-service:8001
      ENVIRONMENT: development
      DEBUG: "true"
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000

  # Optional: Run web in Docker too, but for development use pnpm dev
  # web:
  #   build: ./web
  #   depends_on:
  #     api:
  #       condition: service_healthy
  #   ports:
  #     - "3000:80"
  #   environment:
  #     VITE_API_URL: http://localhost:8000

volumes:
  pgdata: